### ISSUE TITLE
No example project file / compiler suggested. Requires .lib and .h files - link to Microchip don't solve

### ISSUE THREAD

**Issue by ParvCode** [kelray/MCP2221-Examples-for-Windows#1]
I think this is a great library to use but there is no project file or example compiler to even get started and
the Microchip link to libs now use newer libs and support for Visual Studio only,

Tried to use the code but failed with Dev-C++ and Visual Studio 2019.
Wasted so much time. So again - great piece of code but would be nice to get it running on modern compilers.

**Comment by kelray** [comment]
This is not a library, but examples using Microchip Lib and DLL for the MCP2221 for Windows OS only, the examples cannot be used on Linux or Mac OSs.
The project files weren't included on purpose. However, the codes compiles successfully with VS2015 and 2019, also I was able to compile using the MCP2221 library and DLL with Netbeans and MingW C compiler. I don't know much about Dev-C++ IDE, I haven't used it since 2009. I think the errors you are getting might be related to specific configuration on your machine that I'm not aware off.
For what it is worth, the only difference for VS2015 vs 2019 was adding these lines at the beginning of the source code:
```
#ifdef _MSC_VER
#define _CRT_SECURE_NO_WARNINGS
#endif 
```

**Comment by ParvCode** [comment]
Thanks for the tips - spent another hour figuring out for VS2019 as there were other errors related to setting the project up correctly for VS2019 and had to take .h and lib files from one of your other projects which isn't in included in this project but got there in the end.
Still think it helps to provide sample project file for MingW or VS2019 or better.
Thanks,

**Comment by kelray** [comment]
I agree with the principle of adding project files, but because of backward compatibility issues, especially for Visual Studio, I was demotivated from adding the project files. The only exception are projects created using "Qt Creator" IDE, I believe it is easier to fix its compatibility issues. Will try to find a solution for that in future projects.
